# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch


# Create random tensor
random_tensor1 = torch.rand(size = (7 , 7))
random_tensor1 , random_tensor1.dtype


(tensor([[0.5884, 0.8990, 0.4153, 0.9400, 0.0419, 0.5144, 0.4700],
         [0.7792, 0.8588, 0.5556, 0.6037, 0.8827, 0.2432, 0.1936],
         [0.0281, 0.1601, 0.8646, 0.0175, 0.4733, 0.0214, 0.8878],
         [0.4233, 0.7298, 0.6078, 0.1379, 0.2964, 0.3974, 0.3776],
         [0.3008, 0.9998, 0.6992, 0.1011, 0.5750, 0.8967, 0.1585],
         [0.9681, 0.5661, 0.6304, 0.2573, 0.4343, 0.6773, 0.6197],
         [0.2806, 0.4715, 0.9799, 0.8406, 0.8590, 0.3541, 0.5003]]),
 torch.float32)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor

random_tensor2 = torch.rand(size = (1,7))
random_tensor2, random_tensor2.dtype

# Perform matrix multiplication

result = torch.matmul(random_tensor1 , random_tensor2.T)
result


tensor([[2.3186],
        [2.4422],
        [1.3107],
        [1.6140],
        [1.8060],
        [2.5427],
        [2.2742]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors

random_tensor1 = torch.rand(size = (7 , 7))
random_tensor2 = torch.rand(size = (1 , 7))


# Matrix multiply tensors


result = torch.matmul(random_tensor1 , random_tensor2.T)
result , result.shape



(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU

torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)


# Check for access to GPU
print(f"Device: {torch.device('cuda' if torch.cuda.is_available() else '')} \n")


# Create two random tensors on GPU

tensor1 = torch.rand(size = (2 , 3)).cuda()
tensor2 = torch.rand(size = (2 , 3)).cuda()
tensor1 , tensor2


Device: cuda 



(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B

mult = torch.matmul(tensor1 , tensor2.T)
mult , mult.shape


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print(f" maximum : { torch.max(mult)}")

# Find min

print(f" minimum : {torch.min(mult)}")


 maximum : 0.5617256760597229
 minimum : 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(f"the index where the maximum value occurs : {mult.argmax()}")

# Find arg min
print(f"the index where the minimum value occurs : {mult.argmin()}")

the index where the maximum value occurs : 3
the index where the minimum value occurs : 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor_last = torch.rand(size = (1,1,1,10))

# Remove single dimensions
random_tensor_reshape = random_tensor_last.squeeze()


# Print out tensors and their shapes
print(random_tensor_last , random_tensor_last.shape)
print(random_tensor_reshape , random_tensor_reshape.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
